### ISSUE TITLE
TinyMCE not saving any data when its settings are copied from another TinyMCE field

### ISSUE THREAD

**Issue by Hurmeli** [ryancramerdesign/InputfieldTinyMCE#11]
If I have two TinyMCE fields and one copies its settings from another, it will not save anything written in the field. 

Either my upgrade from PW 3.0200 to 3.0206 or your latest TinyMCE upgrade probably caused this, as it was working before.

**Comment by ryancramerdesign** [comment]
@Hurmeli I can't seem to duplicate this issue. I have field "sidebar" inheriting settings from field "body". Body is configured as a Normal editor, default lazy-loading option ("when editor visible"). Can you describe how yours is configured? Also, are you able to open your Javascript console in your browser to see if any errors are present?

Also, when you say "will not save anything written in the field" I'm assuming you are talking about text typed into the field in the page editor, but let me know if I've misunderstood.

**Comment by Hurmeli** [comment]
I meant that saving the page will return the original content, be it empty or filled with text. So you basically cannot change the existing content in the field.

The problem seems to happen when the field where settings are being copied from is set to be inline (my preference as you may have noticed ;). If I change that field to normal from inline, the problem disappears.

My original problem field does NOT suffer from this problem anymore, although I'm not sure what fixed it. For a while I changed it to have its own settings and then changed it back to copy the settings and it happily saves changes made to the content. I have two other fields where the problem still persists.

The screenshot below shows what errors the field itself gives. Letting PW fix these gets rid of all of them except the _lazy. But these don't affect the problem itself.

The tracy error is interesting in that it only happens if backend language is set to english. If I set it to another language it doesn't appear. 

There are no javascript errors.

![Screenshot-(1)](https://user-images.githubusercontent.com/2346230/201612058-e0b4286a-2b12-45f8-b80a-5738581699e4.jpg)

**Comment by ryancramerdesign** [comment]
@Hurmeli Thanks, I was able to duplicate that in Inline Mode also. I have pushed a fix for this. 

Regarding those "Unknown properties", those are properties leftover from CKEditor (other than the _lazy one, which is runtime and can be ignored). If you'd like you can delete those properties, or leave them. I would keep them if you are switching  between TinyMCE and CKEditor on that field, otherwise I'd probably delete them.

**Comment by Hurmeli** [comment]
Cheers!
