### ISSUE TITLE
Path to custom content style css

### ISSUE THREAD

**Issue by esszett** [ryancramerdesign/InputfieldTinyMCE#12]
It’s not a real issue, maybe more  a typo.
In the module settings under "Content style (custom)" where its written "Enter a URL/path to a custom content CSS file. URL should be relative to ProcessWire installation root." It displays as placeholder "Example: /site/templates/styles/mycontent.css".

Entering "/site/templates/tiny-styles/my-styles.css"
leads to 404, TinyMCE is searching for my file @ /site/modules/InputfieldTinyMCE/content_css/my-styles.css

Expected behavior: load my-styles.css from /site/templates/tiny-styles/my-styles.css

"Fix": entering "site/templates/tiny-styles/my-styles.css" without leading slash works.

I'm not sure what's intended, either should the placeholder/notes be corrected or the logic behind custom path?

**Comment by ryancramerdesign** [comment]
Thanks @esszett That was definitely a bug, not a typo. I have pushed a fix. You entered the value correctly the first time: /site/templates/tiny-styles/my-styles.css, and it should work now.

**Comment by esszett** [comment]
It's working now as exptected. Thank you Ryan!
