### ISSUE TITLE
TinyMCE doesn't work inside fieldset

### ISSUE THREAD

**Issue by Hurmeli** [ryancramerdesign/InputfieldTinyMCE#13]
Heya Ryan,

If I put TinyMCE inside a fieldset, all the controls and the textarea field itself will be invisible. You can actually still type stuff in it, but you wont be able to see it.

This is when the TinyMCE is in normal mode. If you set it to inline it will work.

**Comment by ryancramerdesign** [comment]
@Hurmeli I can't seem to duplicate this one. Testing in Normal mode, I tried with an open fieldset, a closed fieldset and an ajax-loaded fieldset. Then I tried different lazy load options (off, on visible, on click). Can you provide any more details on how to duplicate it? Also double check you are running the latest version, as several updates were pushed last week.

**Comment by Hurmeli** [comment]
I just updated the TinyMCE module from 6.0.5 to 6.0.6 and that fixed the issue, sorry for hassle and lets close this one up.
