### ISSUE TITLE
Insert link in a multi-language setup not working correctly.

### ISSUE THREAD

**Issue by erikvanberkum** [ryancramerdesign/InputfieldTinyMCE#14]
Using version 6.0.8 in a multi-language setup.

Standard language is English
Alternative language is Spanish

When doing "Insert Link" in the Spanish text field tab.  
Go to "select page" select an URL. 
After insert link the English URL gets inserted and not the desired Spanish one.

**Comment by ryancramerdesign** [comment]
@erikvanberkum I can't seem to duplicate this one. When I select a page from my non-default language, the inserted link is for the correct language. Is it possible that the page you are linking to is not enabled for Spanish? If all looks good there, can you tell me more about the context of the TinyMCE editor, for instance, is it within a repeater or something?

**Comment by erikvanberkum** [comment]
@ryancramerdesign Sorry Ryan, I tried again, and now it works. Not sure what I did wrong the first, two times before reporting this.
