### ISSUE TITLE
Enabling Invalid styles option breaks the settings page.

### ISSUE THREAD

**Issue by szabeszg** [ryancramerdesign/InputfieldTinyMCE#15]
ProcessWire 3.0.207 dev
TinyMCE rich text editor version 6.2.0.

I installed the module and enabled all the "Optional settings configurable per-field > Invalid styles" option, after that I had tried to save the module settings with "Submit" and I got the following error. From that point on, going to the settings page produces the same error.

	Warning: Array to string conversion in .../wire/modules/Inputfield/InputfieldTextarea.module on line 123

	Fatal Error: Uncaught TypeError: substr_count(): Argument #1 ($haystack) must be of type string, array given in site/modules/InputfieldTinyMCE/InputfieldTinyMCEConfigs.php:1063

	#0 site/modules/InputfieldTinyMCE/InputfieldTinyMCEConfigs.php (1063): substr_count(Array, '\n')
	#1 site/modules/InputfieldTinyMCE/InputfieldTinyMCEConfigs.php (854): InputfieldTinyMCEConfigs->configInvalidStyles('font-size font-...')
	#2 site/modules/InputfieldTinyMCE/InputfieldTinyMCE.module.php(826): InputfieldTinyMCEConfigs->getModuleConfigInputfields(Object(InputfieldWrapper))
	#3 wire/core/Modules.php (4112): InputfieldTinyMCE->getModuleConfigInputfields(Object(InputfieldWrapper))
	#4 wire/core/Wire.php (419): Modules->___getModuleConfigInputfields('InputfieldTinyM...', Object(InputfieldForm))
	#5 wire/core/WireHooks.php (952): Wire->_callMethod('___getModuleCon...', Array)
	#6 wire/core/Wire.php (484): WireHooks->runHooks(Object(Modules), 'getModuleConfig...', Array)
	#7 wire/modules/Process/ProcessModule/ProcessModule.module (1680): Wire->__call('getModuleConfig...', Array)
	#8 wire/modules/Process/ProcessModule/ProcessModule.module (1415): ProcessModule->renderEdit('InputfieldTinyM...', Array)
	#9 wire/core/Wire.php (413): ProcessModule->___executeEdit()
	#10 wire/core/WireHooks.php (952): Wire->_callMethod('___executeEdit', Array)
	#11 wire/core/Wire.php (484): WireHooks->runHooks(Object(ProcessModule), 'executeEdit', Array)
	#12 wire/core/ProcessController.php (350): Wire->__call('executeEdit', Array)
	#13 wire/core/Wire.php (413): ProcessController->___execute()
	#14 wire/core/WireHooks.php (952): Wire->_callMethod('___execute', Array)
	#15 wire/core/Wire.php (484): WireHooks->runHooks(Object(ProcessController), 'execute', Array)
	#16 wire/core/admin.php (160): Wire->__call('execute', Array)
	#17 site/templates/admin.php (103): require('...')
	#18 wire/core/TemplateFile.php (328): require('...')
	#19 wire/core/Wire.php (413): TemplateFile->___render()
	#20 wire/core/WireHooks.php (952): Wire->_callMethod('___render', Array)
	#21 wire/core/Wire.php (484): WireHooks->runHooks(Object(TemplateFile), 'render', Array)
	#22 wire/modules/PageRender.module (575): Wire->__call('render', Array)
	#23 wire/core/Wire.php (416): PageRender->___renderPage(Object(HookEvent))
	#24 wire/core/WireHooks.php (952): Wire->_callMethod('___renderPage', Array)
	#25 wire/core/Wire.php (484): WireHooks->runHooks(Object(PageRender), 'renderPage', Array)
	#26 wire/core/WireHooks.php (1060): Wire->__call('renderPage', Array)
	#27 wire/core/Wire.php (484): WireHooks->runHooks(Object(DefaultPage), 'render', Array)
	#28 wire/modules/Process/ProcessPageView.module (184): Wire->__call('render', Array)
	#29 wire/modules/Process/ProcessPageView.module (114): ProcessPageView->renderPage(Object(DefaultPage), Object(PagesRequest))
	#30 wire/core/Wire.php (416): ProcessPageView->___execute(true)
	#31 wire/core/WireHooks.php (952): Wire->_callMethod('___execute', Array)
	#32 wire/core/Wire.php (484): WireHooks->runHooks(Object(ProcessPageView), 'execute', Array)
	#33 index.php (55): Wire->__call('execute', Array)
	#34 {main}
	thrown (line 1063 of site/modules/InputfieldTinyMCE/InputfieldTinyMCEConfigs.php)

**Comment by ryancramerdesign** [comment]
@szabeszg Thanks, I'm going through the issue reports top to bottom and think I just fixed this one in issue #17. Can you confirm?

**Comment by szabeszg** [comment]
@ryancramerdesign I have not yet tested it with a clean PW and module install but I deleted all TinyMCE InputFields I've already created, I updated the module and afterwards I could successfully save the module settings with Invalid styles option turned on.
In short: it seems to have been fixed. Thank you!
