### ISSUE TITLE
Default setting overrides JSON text: blank object

### ISSUE THREAD

**Issue by chriswthomson** [ryancramerdesign/InputfieldTinyMCE#20]
When passing an empty object `{}` as a value in the *Default setting overrides JSON text* field, it is evaluated as an empty array not an object:

Setting:
```json
{
	"table_default_attributes": {},
	"table_default_styles": {},
}
```

Result: (ProcessWire.config.InputfieldTinyMCE....)
```javascript
{
	table_default_attributes: [],
	table_default_styles: [],
}
```

I assume this is to do with PHP's `json_decode`. Something like this might fix it:

```php
$custom = json_decode($str, 1);
foreach($custom as $key => $value) {
	if(is_array($value) && empty($value) && strpos($str, $key . ': {}') !== false) {
		$custom[$key] = (object) $value;
	}
}
```

**Comment by ryancramerdesign** [comment]
Thanks @chriswthomson I've pushed a fix for this on the core dev branch. Can you confirm it also fixes it for you?

**Comment by chriswthomson** [comment]
Yes thanks @ryancramerdesign, that seems to have resolved it.

Will pop any future issue reports into the PW issues repo.

Cheers,

Chris
