### ISSUE TITLE
Align left and right adds float to text

### ISSUE THREAD

**Issue by Hurmeli** [ryancramerdesign/InputfieldTinyMCE#6]
Using align left & right adds the align_ class, which basically floats the element left or right. This is probably only wanted behaviour if it's being set to an image, entire table and some other similar cases.

Perhaps the default behaviour should just be text-align: left/right. Now if you try to align text be it paragraph or text inside a td, things get rather funky.

**Comment by ryancramerdesign** [comment]
@Hurmeli Looks like it was just doing that for inline mode, as a result of inheriting admin theme styles. I've updated our default content.css to override and correct those styles for inline mode so that they just use text-align without float. Thanks.

**Comment by Hurmeli** [comment]
That makes sense. I should really try out the non-inline version, but to be honest I much prefer the way inline version looks and works. It just gives a better, non cluttered user experience in my opinion.
