### ISSUE TITLE
Reflect current admin/field language setting in TinyMCE html

### ISSUE THREAD

**Issue by esszett** [ryancramerdesign/InputfieldTinyMCE#8]
It would be helpful to have the current admin and field language settings reflected as attributes (lang and dir) in TinyMCE html tag. As I'm using the q tag wrapped with quotes (e.g. de: „“ en: ““) via css dependent on the html lang attribute.

**Comment by ryancramerdesign** [comment]
@esszett I don't think we have control over custom attributes unless using inline mode. In inline mode, PW's existing lang attribute (on the html tag) is already present and within the scope of the inline editor. We could add a dir attribute in PW too.

For the normal/regular (non-inline) editor, that is rendered in a separate iframe document by TinyMCE. In there, I don't see that we can add custom attributes, though I could be wrong. TinyMCE does have the [body_class](https://www.tiny.cloud/docs/tinymce/6/add-css-options/#body_class) and body_id attributes that we can populate, if either of those would provide what you need?

Also, just checked and in Normal  mode, TinyMCE does populate a `dir=ltr` (or rtl) attribute to the `<body>` tag, but I don't see that it populates a lang attribute anywhere.

**Comment by esszett** [comment]
I stumbled across this issue, while replacing ckeditor, who gets that attribute. But no problem, I recognized the data-id attribute in .mce-content-body, so I can use a selector like .mce-content-body[data-id*="_1024"] to get the same result in the corresponding language version of a field now. Please close. Thank you Ryan.

**Comment by ryancramerdesign** [comment]
Okay great, glad that works, thank for letting me know.
