### ISSUE TITLE
TinyMCE not initialized (in FieldsetOpen)

### ISSUE THREAD

**Issue by esszett** [ryancramerdesign/InputfieldTinyMCE#9]
Setup fields @tpl
- "text": Textarea Multilanguage field, Type TinyMCE
- "wrap": FieldsetOpen, inital display is set to **closed**

TinyMCE doesn't get initialized when trying to edit field "text" after opening "wrap".
expected behavior: on pageedit, opening the closed fieldset "wrap" should trigger the nested field "text" to load TinyMCE.

---
SERVER DETAILS
ProcessWire: 3.0.200
PHP: 8.0.23
Webserver: Apache/2.4.54 (Unix) OpenSSL/1.1.1q 
MySQL Server: 5.7.39
MySQL Client: mysqlnd 8.0.23

**Comment by ryancramerdesign** [comment]
Thanks @esszett I think I've got that issue fixed, are you able to test to confirm?

**Comment by esszett** [comment]
I've done my tests, also nested in repeater items – it works. Thank you for the quick fix!
